#!/bin/bash
#
# Behavior:
#   Userscript for qutebrowser which reads the output of wl-paste and yanks it
#   to make it available in the browser.

#   This is merely because with Wayland on Gnome-shell, while copying from
#   Qutebrowser works just fine, copying *from* other applications to
#   Qutebrowser does not always work.

#   Note: requires that wl-paste is installed

#   If run as a command (:spawn --userscript yankhelper), 
#   Example:
#       :spawn --userscript yankhelper
#
# Ankur Sinha (sanjayankur31@github), 2020.
# Any feedback is welcome!

function yankfromwlclipboard ()
{
# Remove hyphenated line endings, then escape the backslashes, then remove the
# line endings.
# Must use tr since sed only acts line by line and will not combine two lines.
# The backslashes need to be escaped for qutebrowser.

    clipboard_contents="$(wl-paste | sed -E -e 's/-[\r\n]$//' -e 's/\\/\\\\/g' | tr -d -- '\n\r')"

    printf 'yank inline "%s"' "$clipboard_contents" > "$QUTE_FIFO"
}

function yankfromselection ()
{
    printf 'yank inline "%s"' "$QUTE_SELECTED_TEXT" > "$QUTE_FIFO"
}

function usage()
{
    echo "yankhelper: userscript for yanking things in Qutebrowser"
    echo
    echo "Usage:"
    echo "yankhelper [-w | -s]"
    echo
    echo "-w: yank from wayland clipboard: requires wl-paste, removed newlines and carriage returns"
    echo "-s: yank selected text into clipboard for usage elsewhere"
}

while getopts "ws" OPTION
do
    case $OPTION in
        w)
            yankfromwlclipboard
            exit 0
            ;;
        s)
            yankfromselection
            exit 0
            ;;
        h)
            usage
            exit 0
            ;;
        ?)
            echo "Nothing to do."
            usage
            exit 1
            ;;
    esac
done
